MVC3Pet/Mvc3Pet/Controllers/ShoppingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FlcalPriceRD;

namespace MvcFocalPrice.Controllers
{
    public class ShoppingController : Controller
    {
        FocalpriceEntities db = new FocalpriceEntities();
        //
        // GET: /Shopping/

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var db = new FocalpriceEntities();
            var coll = (from c in db.Countries
                       select new SelectListItem
                       {
                           Text = c.Name,
                           Value = c.Code
                       }).ToList();
            if (Session["countrycode"] != null)
            {
                var countrycode = Session["countrycode"].ToString();
                ViewBag.selectcountrycode = countrycode;
                ViewBag.shippingfee = cart.GetShippingFee(countrycode).ToString("C");
                ViewBag.ground = (cart.GetTotal() + cart.GetShippingFee(countrycode)).ToString("C");
                // initial select country 
                var item = coll.Single(t => t.Value.Trim() == countrycode);
                item.Selected = true;
            }
            else
            {
                coll.Insert(0, new SelectListItem { Text="-- Please select your country --", Value = "-1", Selected = true});
            }

            ViewBag.countrycoll = coll.OrderBy(t=>t.Text);

            // Set up ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),
                ItemTotal = cart.GetCount()
            };
            return View(viewModel);
        }

        public ActionResult AddToCart(int id, int qty)
        {
            // Retrieve the product from database
            var addedproduct = db.Products.Single(p => p.ID == id);
           
            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedproduct, qty);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int productid, string cartid, string countrycode)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the product to display confirmation
            var cartitem = db.ShoppingCarts
                .Single(item => item.ProductID == productid && item.CartID == cartid);
            var productname = cartitem.Product.Name;

            // Remove from cart
            //int itemCount = cart.RemoveFromCart(cartitem);
            db.ShoppingCarts.DeleteObject(cartitem);
            db.SaveChanges();

            var carttotal = cart.GetTotal();

            var shippingfee = cart.GetShippingFee(countrycode);

            var grandtotal = carttotal + shippingfee;

            if (shippingfee == -1m)
            {
                grandtotal = -1m;
            }


            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(productname) +
                    " has been removed from your shopping cart.",
                CartTotal = carttotal,
                CartCount = cart.GetCount(),
                ItemCount = 0,
                DeleteId = cartitem.ProductID,
                GrandTotal = grandtotal,
                ShippingFee = shippingfee
            };

            return Json(results);
        }

        [HttpPost]
        public ActionResult CalculateShipping(string countrycode)
        {
            Session["countrycode"] = countrycode;
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var shippingfee = cart.GetShippingFee(countrycode);

            var carttotal = cart.GetTotal();
            var grandtotal = carttotal + shippingfee;

            if (shippingfee == -1m)
            {
                grandtotal = -1m;
            }

            var results = new ShoppingCartCountryChangeViewModel
            {
                ShippingFee = shippingfee,
                GrandTotal = grandtotal
            };

            return Json(results);
        }

        [HttpPost]
        public ActionResult CartQtyChange(int productid, string cartid, int qty, string countrycode)
        {

            var db = new FocalpriceEntities();

            var cartitem = db.ShoppingCarts
                .Single(item => item.ProductID == productid && item.CartID == cartid);
            var productname = cartitem.Product.Name;

            cartitem.Quantity = qty;
            db.SaveChanges();

            var subtotal = (int?)qty * cartitem.Product.Price;

            var cart = ShoppingCart.GetCart(this.HttpContext);

            var carttotal = cart.GetTotal();

            var shippingfee = cart.GetShippingFee(countrycode);

            var grandtotal = carttotal + shippingfee;

            if (shippingfee == -1m)
            {
                grandtotal = -1m;
            }

            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(productname) +
                    " has been removed from your shopping cart.",
                CartTotal = carttotal,
                CartCount = cart.GetCount(),
                SubCartTotal = (Decimal)subtotal,
                ItemCount = 0,
                DeleteId = cartitem.ProductID,
                GrandTotal = grandtotal,
                ShippingFee = shippingfee
            };

            return Json(results);
        }

        [Authorize]
        public void ProcessPaypal(string grandtotal, string shippingfee, string selectcountry)
        {
            //return RedirectToAction("Index", "Paypal", new { grandtotal = Convert.ToDecimal(grandtotal), shippingfee = Convert.ToDecimal(shippingfee), selectcountry = selectcountry });
            RedirectToAction("Index", "Paypal");
        }

        // GET: /ShoppingCart/CartSummary

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);  

            ViewBag.CartCount = cart.GetCount();

            return PartialView("CartSummary");
        }

    }
}

MVC3Pet/Mvc3Pet/Views/Shared/CategoryMenu.cshtml
@model IEnumerable<FlcalPriceRD.Category>
<div class="grid_col_sub">
    <script type="text/javascript">
        $(function () {
            $("#dsmenu > li").each(function () {
                if ($(this).children("ul").length != 0) {
                    $(this).children("span").toggle(function () {
                        $(this).parent("li").addClass("expand");
                        $(this).parent().contents("ul").show();
                    }, function () {
                        $(this).parent("li").removeClass("expand");
                        $(this).parent().contents("ul").hide();
                    })
                }
            });
            var x = "@ViewBag.exp";
            if (x != '') {
                $("#dsmenu li:nth-child(" + x + ") span").click();
            }
        });
    </script>
    <div class="revieweditems mt10">
        <div class="revieweditems_h">
            <h1 class="fleft" id="parent_categoryname">Pet Supplies</h1>
        </div>
        <div id="dsav">
            <ul>
                @foreach (var item in @Model)
                {
                    <li class="nochildren"><span></span><a title="" class="sub_category_name" href="/category/@item.ID/@item.Name.Replace(" & ", "-").Replace(" ", "-")">@item.Name</a></li>
                }
            </ul>
        </div>
    </div>
    <div style="text-align: center; margin-top: 20px">
       @* <a href="http://stores.ebay.com/24sell24" target="_blank">
            <img src="../../Content/Images/ebaystore.jpg" alt="ebaystore" />
        </a>
        <br /><br />
        <a href="https://www.etsy.com/shop/petsmartpm" target="_blank">
            <img src="../../Content/Images/etsy%20shop.jpg" alt="etsystore" />
        </a>
        <br /><br />
        <a href="http://www.ioffer.com/selling/24sell24 " target="_blank">
            <img src="../../Content/Images/iofferstore.jpg" alt="iofferstore" />
        </a>*@
    </div>
    <br />
</div>

MVC3Pet/Mvc3Pet/Views/Shared/ProductList.cshtml
@model List<FlcalPriceRD.ViewModels.ProductListViewModel>
@{
    var pageno = ViewBag.pageno;
    var categoryproductcountlist = (List<MvcFocalPrice.Controllers.categoryproductcount>)ViewBag.categoryproductcountlist;
    var description = (FlcalPriceRD.Category)ViewBag.catedescript;
    var totalpage = (int)ViewBag.totalpage;
}
<div class="grid_col_main">
    <div class="grid_main_wrap mt10">
        <div id="cate_describe" class="cate_describe">
            <h1 class="f14 c00 pb5">
                <a href="../../category/@description.ID/@description.Name.Replace(" ", "").Replace('&', '-')">@description.Name</a>
            </h1>
            <em></em>
        </div>
        @if (categoryproductcountlist != null)
        {
            <div id="conditionContent" class="search_list w940 mauto mt10">
                <div class="search_list_t" id="condition_refine">
                    <div class="search_list_t_title c00 f14 fleft mr10">
                        <span class="db fleft search_list_t_title_ico un" style="display: none"></span><span
                            class="db fleft">Refine By:</span>
                    </div>
                </div>
                <div class="search_list_box clearfix search_attributes_mark" style="position: relative">
                    <div class="search_list_box_r w850" id="cate" style="z-index: 3">
                        @foreach (var item in categoryproductcountlist)
                        {
                            <div class="catelist w135 classify">
                                <div class="catelist_first">
                                    <a class="catelist_Dmenu" href="/category/@item.ID/@item.CategoryName.Replace(" & ", "-").Replace(" ", "-").Replace(@"""", "")">
                                        <abbr>
                                            @item.CategoryName</abbr><em>(@item.ProductCount)</em></a>
                                </div>
                            </div>
                        }
                        <div class="catelist_more f11">
                            More</div>
                    </div>
                </div>
            </div>
        }
        <div class="listhead mt10" id="filter_view">
            <ul class="tabs fleft">
                <li class="active fleft"><a><em id="all_item_count" style="font-weight:bold">All Items(@ViewBag.producttotal)</em></a></li>
            </ul>
            <div class="fleft mr10">
            </div>
            <div class="fright list_sort">
                <span class="fleft fb">Sort by: </span>
                @Html.ActionLink("Lowest Price", "Index", new { orderby = "lowestprice", exp = ViewBag.exp})
                @Html.ActionLink("Highest Price", "Index", new { orderby = "highestprice", exp = ViewBag.exp})
            </div>
        </div>
            <div id="list_content" class="items addborder">
                @foreach (var item in Model)
                {
                    <div class="itembox ml15 mb20">
                        <ul class="infobox">
                            <li><a href="/product/@item.ID/@item.Name.Replace("+", "-").Replace("/", "-").Replace(" & ", "-").Replace(" ", "-").Replace(@"""", "").Replace(@":", "-")">
                                <img src="/FeaturePic/@item.picname" alt="@item.Name" style="width:155px" />
                            </a><span class="pro_instock"></span></li>
                            <li class="proName f11"><a title="@item.Name" href="/product/@item.ID/@item.Name.Replace("+", "-").Replace("/", "-").Replace(" & ", "-").Replace(" ", "-").Replace(@"""", "").Replace(@":", "-")">
                                @item.Name</a></li>
                            <li class="proPri"><span>US @item.Price.ToString("C")</span></li>
                            <li class="freeShip">Free Shipping </li>
                        </ul>
                    </div>
                } 
            </div>
        <div class="clear">
        </div>
        <div class="pages fright">
            <span>Pages: @pageno/@totalpage</span>
            @Html.ActionLink(" ", "index", new { pageno = 1, orderby = (string)ViewBag.sort }, new { @class = "prevall" })
            @Html.ActionLink(" ", "index", new { pageno = pageno == 1 ? 1 : pageno - 1, orderby = (string)ViewBag.sort }, new { @class = "prev" })
            @if (@totalpage <= 7)
            {
                for (int i = 1; i <= totalpage; i++)
                {
                    if (i == pageno)
                    {
                         <a class="current">@i</a>
                    }
                    else
                    {
                        @Html.ActionLink(i.ToString(), "index", new { pageno = i, orderby = (string)ViewBag.sort })
                    }
                }
            }
            else
            {
                if (@pageno <= 4)
                {
                    for (int i = 1; i <= pageno + 2; i++)
                    {
                        if (i == pageno)
                        {
                             <a class="current">@i</a>
                        }
                        else
                        {
                            @Html.ActionLink(i.ToString(), "index", new { pageno = i, orderby = (string)ViewBag.sort })
                        }
                    }
                    <span href="#" class="ellipsis"> ....</span>
                    @Html.ActionLink(totalpage.ToString(), "index", new { pageno = totalpage, orderby = (string)ViewBag.sort })
                }
                else
                {
                    if (totalpage <= pageno + 3)
                    {
                        @Html.ActionLink("1", "index", new { pageno = 1, orderby = (string)ViewBag.sort })
                        <span href="#" class="ellipsis"> ....</span>
                        for (int i = pageno - 2; i <= totalpage; i++)
                        {
                            if (i == pageno)
                            {
                                 <a class="current">@i</a>
                            }
                            else
                            {
                                @Html.ActionLink(i.ToString(), "index", new { pageno = i, orderby = (string)ViewBag.sort })
                            }
                        }
                    }
                    else
                    {
                         @Html.ActionLink("1", "index", new { pageno = 1, orderby = (string)ViewBag.sort })
                        <span href="#" class="ellipsis"> ....</span>
                        for (int i = pageno - 2; i <= pageno + 2; i++)
                        {
                            if (i == pageno)
                            {
                                 <a class="current">@i</a>
                            }
                            else
                            {
                                @Html.ActionLink(i.ToString(), "index", new { pageno = i, orderby = (string)ViewBag.sort })
                            }
                        }
                        <span href="#" class="ellipsis"> ....</span>
                         @Html.ActionLink(totalpage.ToString(), "index", new { pageno = totalpage, orderby = (string)ViewBag.sort })
                    }
                }
            }
            @Html.ActionLink(" ", "index", new { pageno = pageno == @totalpage ? pageno : pageno + 1, orderby = (string)ViewBag.sort }, new { @class = "next" })
            @Html.ActionLink(" ", "index", new { pageno = @totalpage, orderby = (string)ViewBag.sort }, new { @class = "nextall" })
            <div class="clear">
            </div>
        </div>
    </div>
</div>

MVC3Pet/Mvc3Pet/Views/Shared/_AdminMenu.cshtml
    <ul>
        <li><a href="@Url.Content("~/Warranty")">Product Warranty</a></li>
        <li><a href="@Url.Content("~/ReturnPolicy")">Return Policy</a></li>
        <li><a href="@Url.Content("~/TermofUse")">Term of Use</a></li>
        <li><a href="@Url.Content("~/PrivacyPolicy")">Privacy &amp; Security Policy</a></li>
    </ul>

MVC3Pet/Mvc3Pet/Views/Shared/_HelpMenu.cshtml
<div class="HelpCate">
    <h4>
        <a>Policy</a></h4>
    <ul>
        @*<li><a href="@Url.Content("~/Warranty")">Product Warranty</a></li>*@
        @*<li><a href="@Url.Content("~/ReturnPolicy")">Return Policy</a></li>*@
        <li><a href="/TermofUse">Term of Use</a></li>
        <li><a href="/PrivacyPolicy">Privacy &amp; Security Policy</a></li>
        <li><a href="/Shipping">Shipping</a></li>
    </ul>
    @*<h4>
        <a>FAQs</a></h4>
    <ul>
        <li><a>Payment </a></li>
        <li><a>Shipping </a></li>
        <li><a>Ordering</a></li>
    </ul>*@
    <h4> 
        <a>Company Info</a></h4>
        <ul>
    <li><a href="/AboutUs">About Us</a></li>
    <li><a href="/ContactUs">Contact Us</a></li>
    </ul>
</div>

MVC3Pet/Mvc3Pet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/global.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/layout.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/list.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/product.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/common.css")" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="http://www.focalprice.com/Views/favicon.ico" />
    <link rel="stylesheet" rev="stylesheet" id="skin" type="text/css" media="all" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/screen.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.watermark.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.alphanumeric.pack.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $("#keyword").watermark("Enter keywords to search in our products");

            $("#btnsearch").click(function () {
                var keyword = $("#keyword").val();
                location.href = @Url.Content("/search/") + keyword;
            });

            var css_url1024x768 = "../../Content/1024.css";
            if (screen.width < 1200 || $(window).width() < 1200) {
                $("#skin").attr("href", css_url1024x768);
            }
            $(window).resize(function () {
                if ($(window).width() < 1200) {
                    $("#skin").attr("href", css_url1024x768);
                } else {
                    $("#skin").removeAttr("href", "");
                }
            });
            setTimeout(function () { goTop() }, 500);
        })
    </script>
    <meta name="google-site-verification" content="GZ7lZ1_LUnyyUE0vtiGwZEJZl_-Em8SRwxpFMqCFK-Y" />
</head>
<body>
    <div id="topmenu" class="mauto">
        <ul class="topmenu_l fleft">
            <li class="fleft home"><a class="cf50" href="/">Home</a></li>
        </ul>
        <ul class="topmenu_r fright">
            <li class="fright f11" style="margin-left:5px; margin-right:15px"><a href="/AboutUs">Help</a></li>
            <li class="fright line"></li>
            <li class="fright account f11"><a class="selMenu" id="selMenu" href="/Account/LogOn">My
                Account</a> <span></span></li>
            <li class="fright line"></li>
            @Html.Partial("_LogOn")
        </ul>
    </div>
    <div class="mauto headerin mb10">
        <div class="fleft"><br />
            <a title="Welcome to petsmartpm!" style="margin-left:10px" href="/"><img src="../../cssimage/logo.png"/></a></div>
        <div class="search_warp fright">
            <div style="float:left; width:720px">
                <input name="keyword" class="fleft headinput" id="keyword" value="" type="text" size="50" />
                <input type="submit" id="btnsearch" class="btn_search fleft" value="" /><br /><br /><br />
                <label style="font-weight:bold">Popular Searches:</label>
                    <a style="text-decoration:underline; margin-left:5px" href="/search/Coat">Coat</a>
                     <a style="text-decoration:underline;margin-left:5px" href="/search/Carrier">Carrier</a>
                      <a style="text-decoration:underline;margin-left:5px" href="/search/Dress">Dress</a> 
                      <a style="text-decoration:underline;margin-left:5px" href="/search/Skirt">Skirt</a> 
                      <a style="text-decoration:underline;margin-left:5px" href="/search/Tote">Tote</a>
                      <a style="text-decoration:underline;margin-left:5px" href="/search/Bed">Bed</a> 
                      <a style="text-decoration:underline;margin-left:5px" href="/search/Bowl">Bowl</a>
                      <a style="text-decoration:underline;margin-left:5px" href="/search/Travel">Travel</a>
                      <a style="text-decoration:underline;margin-left:5px" href="/search/Bag">Bag</a>
                      <a style="text-decoration:underline;margin-left:5px" href="/search/Leash">Leash</a>
                      <a style="text-decoration:underline;margin-left:5px" href="/search/Toy">Toy</a>
                <div class="clear">
                </div>
            </div>
            <div class="homecart fleft">
                @{Html.RenderAction("CartSummary", "Shopping");}
            </div>
        </div>
        <div class="clear">
        </div>
            <div style="height:2px; margin-top:10px; background-color:#1c6cbe"></div>
    </div>

    <div class="grid_main clearfix" style="min-height:600px">
        <div class="col_main">
            @RenderBody()
        </div>
    </div>
    <div id="footer">
        <div class="copyright f11">
            <img src="../../cssimage/footbanner.PNG" /><br />
            &#169; 2012 www.petsmartpm.com All rights reserved.
        </div>
    </div>
</body>
</html>

MVC3Pet/Mvc3Pet/Views/Shared/_LogOn.cshtml
@if(Request.IsAuthenticated) {
     <text><li  class="fright f11">  @Html.RouteLink("Log Off", "default", new { controller = "Account", action = "LogOff" }, new { @style = "margin-right:10px;" })</li>
   <li  class="fright f11">Welcome <strong style="margin-right:5px">@User.Identity.Name</strong></li>
  </text>
}
else
{
   @*@Html.ActionLink(" Log On", "LogOn", "Account", new { @class = "selMenu" })*@
   <li  class="fright f11">@Html.RouteLink("Sign in or Register", "default", new { controller = "Account", action = "LogOn" }, new { @class = "selMenu", @style="margin-right:10px" })</li>
   @*<a href="@Url.Content("~/Account/Logon")" class="selMenu"> Log On</a>*@
}