MVC3Pet/Backup/Mvc3Pet/Controllers/EditProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FlcalPriceRD;

namespace MvcFocalPrice.Controllers
{ 
    [Authorize(Users = "mylok")]
    public class EditProductController : Controller
    {
        private FocalpriceEntities db = new FocalpriceEntities();

        //
        // GET: /EditProduct/

        public ViewResult Index()
        {
            var products = db.Products;
            return View(products.ToList());
        }

        public ViewResult Index2()
        {
            var products = db.Products.Take(10);
            return View(products.ToList());
        }


        //
        // GET: /EditProduct/Details/5

        public ViewResult Details(int id)
        {
            Product product = db.Products.Single(p => p.ID == id);
            return View(product);
        }

        //
        // GET: /EditProduct/Create

        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories.Where(c=>c.ParentID != null), "ID", "Name"); 
            return View();
        } 

        //
        // POST: /EditProduct/Create

        [HttpPost]
        public ActionResult Create(Product product, string txtimg1, string txtimg2, string txtimg3, string txtimg4, string txtimg5, string txtimg6, string txtimg7, string txtimg8, string txtimg9)
        {
            if (ModelState.IsValid)
            {
                db.Products.AddObject(product);
                var newmatch = new productcategorymatch
                {
                    categoryid = product.CategoryID,
                    productid = product.ID
                };
                db.productcategorymatches.AddObject(newmatch); 
                db.SaveChanges();

                InsertPic(product, product.ImgName);
                InsertPic(product, txtimg2);
                InsertPic(product, txtimg3); 
                InsertPic(product, txtimg4);
                InsertPic(product, txtimg5);
                InsertPic(product, txtimg6);
                InsertPic(product, txtimg7);
                InsertPic(product, txtimg8);
                InsertPic(product, txtimg9);
                return RedirectToAction("Index");  
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        private void InsertPic(Product product, string txtimg)
        {
            if (!string.IsNullOrWhiteSpace(txtimg))
            {
                var pic = new ProductImage
                {
                    ProductID = product.ID,
                    IsFeature = true,
                    Name = txtimg
                };
                db.ProductImages.AddObject(pic);
                db.SaveChanges();
            }
        }
        
        //
        // GET: /EditProduct/Edit/5
 
        public ActionResult Edit(int id)
        {
            Product product = db.Products.Single(p => p.ID == id);
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", db.Categories.Single(t=>t.ID == product.CategoryID));
            ViewBag.Coll = db.Categories;
            ViewBag.CategoryName = db.Categories.Single(c => c.ID == product.CategoryID).Name;
            return View(product);
            //var model = new ProductEditModel
            //{
            //    SelectProductCategoryID = product.CategoryID,
            //    SelectProduct = product,
            //    CategoryColl = db.Categories
            //};
        }

        //
        // POST: /EditProduct/Edit/5

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Attach(product);
                db.ObjectStateManager.ChangeObjectState(product, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            // ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        //
        // GET: /EditProduct/Delete/5
 
        public ActionResult Delete(int id)
        {
            Product product = db.Products.Single(p => p.ID == id);
            return View(product);
        }

        //
        // POST: /EditProduct/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Product product = db.Products.Single(p => p.ID == id);
            db.Products.DeleteObject(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MVC3Pet/Backup/Mvc3Pet/Views/EditProduct/Create.cshtml
@model FlcalPriceRD.Product
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link href="../../Content/jHtmlArea.css" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="../../Scripts/jHtmlArea-0.7.5.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $("#txtareadescription").htmlarea();
        });
    </script>
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <legend>Product</legend>
            <div class="editor-label">
                @Html.LabelFor(model => model.CategoryID, "Category")
            </div>
            <div class="editor-field">
                @Html.DropDownList("CategoryID", String.Empty)
                @Html.ValidationMessageFor(model => model.CategoryID)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Price)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
            @*            <div class="editor-label">
                @Html.LabelFor(model => model.Price3)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Price3)
                @Html.ValidationMessageFor(model => model.Price3)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Price5)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Price5)
                @Html.ValidationMessageFor(model => model.Price5)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Price10)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Price10)
                @Html.ValidationMessageFor(model => model.Price10)
            </div>
*@
            <div class="editor-label">
                @Html.LabelFor(model => model.Sku)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Sku)
                @Html.ValidationMessageFor(model => model.Sku)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.ItemDescription)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.ItemDescription, new { @id = "txtareadescription", @style = "width:500px; height:200px" })
                @Html.ValidationMessageFor(model => model.ItemDescription)
            </div>
            <br /><br />
            <!-- Insert PetProductImage -->
            <label>Feature Image : </label>
              @Html.EditorFor(model => model.ImgName)
                @Html.ValidationMessageFor(model => model.ImgName)
            <label style="margin-left:30px">Image1 : </label>
            <input type="text" name="txtimg2" style="width:150px" />
            <label style="margin-left:30px">Image2 : </label>
            <input type="text" name="txtimg3" style="width:150px" /><br /><br />
           <label>Image3 : </label>
            <input type="text" name="txtimg4" style="width:150px" />
           <label style="margin-left:30px">Image4 : </label>
            <input type="text" name="txtimg5" style="width:150px" />
           <label style="margin-left:30px">Image5 : </label>
            <input type="text" name="txtimg6" style="width:150px" /><br/><br />
             <label>Image6 : </label>
            <input type="text" name="txtimg7" style="width:150px" />
           <label style="margin-left:30px">Image7 : </label>
            <input type="text" name="txtimg8" style="width:150px" />
           <label style="margin-left:30px">Image8 : </label>
            <input type="text" name="txtimg9" style="width:150px" />

            @*  
            <div class="editor-label">
                @Html.LabelFor(model => model.Title)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
    
          <div class="editor-label">
                @Html.LabelFor(model => model.IsAvailable)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IsAvailable)
                @Html.ValidationMessageFor(model => model.IsAvailable)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ImgName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ImgName)
                @Html.ValidationMessageFor(model => model.ImgName)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Meta)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Meta)
                @Html.ValidationMessageFor(model => model.Meta)
            </div>
    *@
            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

MVC3Pet/Backup/Mvc3Pet/Views/EditProduct/Delete.cshtml
@model FlcalPriceRD.Product

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <fieldset>
        <legend>Product</legend>
    
        <div class="display-label">Category</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Category.Name)
        </div>
    
        <div class="display-label">Name</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Name)
        </div>
    
        <div class="display-label">Price</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Price)
        </div>
    
        <div class="display-label">Price3</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Price3)
        </div>
    
        <div class="display-label">Price5</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Price5)
        </div>
    
        <div class="display-label">Price10</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Price10)
        </div>
    
        <div class="display-label">Sku</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Sku)
        </div>
    
        <div class="display-label">ItemDescription</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ItemDescription)
        </div>
    
        <div class="display-label">Title</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Title)
        </div>
    
        <div class="display-label">IsAvailable</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.IsAvailable)
        </div>
    
        <div class="display-label">ImgName</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ImgName)
        </div>
    
        <div class="display-label">Meta</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Meta)
        </div>
    </fieldset>
    @using (Html.BeginForm()) {
        <p>
            <input type="submit" value="Delete" /> |
            @Html.ActionLink("Back to List", "Index")
        </p>
    }

</body>
</html>

MVC3Pet/Backup/Mvc3Pet/Views/EditProduct/Details.cshtml
@model FlcalPriceRD.Product

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Details</title>
</head>
<body>
    <fieldset>
        <legend>Product</legend>
    
        <div class="display-label">Category</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Category.Name)
        </div>
    
        <div class="display-label">Name</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Name)
        </div>
    
        <div class="display-label">Price</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Price)
        </div>
    
        <div class="display-label">Price3</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Price3)
        </div>
    
        <div class="display-label">Price5</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Price5)
        </div>
    
        <div class="display-label">Price10</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Price10)
        </div>
    
        <div class="display-label">Sku</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Sku)
        </div>
    
        <div class="display-label">ItemDescription</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ItemDescription)
        </div>
    
        <div class="display-label">Title</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Title)
        </div>
    
        <div class="display-label">IsAvailable</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.IsAvailable)
        </div>
    
        <div class="display-label">ImgName</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ImgName)
        </div>
    
        <div class="display-label">Meta</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Meta)
        </div>
    </fieldset>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

MVC3Pet/Backup/Mvc3Pet/Views/EditProduct/Edit.cshtml
@model FlcalPriceRD.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<link href="../../Content/jHtmlArea.css" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="../../Scripts/jHtmlArea-0.7.5.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        $("#test").htmlarea();
    });
</script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Product</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryID)
            @Html.ValidationMessageFor(model => model.CategoryID)
            @*@Html.DropDownListFor(model=>model.CategoryID, new SelectList(ViewBag.Coll, "ID", "Name", 7), new {@style= "width:200px"})*@
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price) 
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price3)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price3)
            @Html.ValidationMessageFor(model => model.Price3)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price5)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price5)
            @Html.ValidationMessageFor(model => model.Price5)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price10)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price10)
            @Html.ValidationMessageFor(model => model.Price10)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Sku)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Sku)
            @Html.ValidationMessageFor(model => model.Sku)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ItemDescription)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.ItemDescription, new { @id = "test", @style = "width:500px; height:200px" })
            @Html.ValidationMessageFor(model => model.ItemDescription)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsAvailable)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsAvailable)
            @Html.ValidationMessageFor(model => model.IsAvailable)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ImgName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ImgName)
            @Html.ValidationMessageFor(model => model.ImgName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Meta)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Meta)
            @Html.ValidationMessageFor(model => model.Meta)
        </div>
         <div class="editor-label">
            @Html.LabelFor(model => model.Weight)
        </div>
         <div class="editor-field">
            @Html.EditorFor(model => model.Weight)
            @Html.ValidationMessageFor(model => model.Weight)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC3Pet/Backup/Mvc3Pet/Views/EditProduct/Index.cshtml
@model IEnumerable<FlcalPriceRD.Product>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>EditProduct</title>
    <link href="../../Content/DataTables/css/demo_table.css" rel="stylesheet" type="text/css" />
    <link href="../../Content/DataTables/css/demo_page.css" rel="stylesheet" type="text/css" />
    <script src="../../Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="../../Scripts/jquery.dataTables.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $("#producttable").dataTable({
                "iDisplayLength": 25,
                "aLengthMenu": [[15, 25, 50, -1], [15, 25, 50, "All"]]
            });
        });
    </script>
</head>
<body>
    <div>
        @Html.ActionLink("Back to home page", "Index", "Home");
        <br /><br />
        <table id="producttable" class="display">
            <thead>
                <tr>
                    <th>Sku</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>IsAvailable</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.ActionLink((string)item.Sku, "Edit", new { id = item.ID })</td>
                        <td>@item.Name</td>
                        <td>@item.Price.ToString("C")</td>
                        <td>@item.IsAvailable</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

MVC3Pet/Backup/Mvc3Pet/Views/EditProduct/Index2.cshtml
@model IEnumerable<FlcalPriceRD.Product>
@helper Truncate(string input, int length)
    {
        if (input.Length <= length)
        {
    @input
        }
        else
        {
    @input.Substring(0, length)<text>...</text>
        }
}
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Index</title>
    <style type="text/css">
        /* Tables */
        table
        {
            border: 1px solid #000;
            border-collapse: collapse;
            color: #666666;
            min-width: 500px;
            width: 100%;
        }
        
        tr
        {
            border: 1px solid #000;
            line-height: 25px;
        }
        
        th
        {
            background-color: #9b9993;
            color: #000;
            font-size: 13px;
            text-align: left;
        }
        
        th, td
        {
            padding-left: 5px;
        }
        
        tr:hover
        {
            background-color: #fff;
        }
        a:link, a:visited
        {
            color: #F6855E;
            text-decoration: none;
            font-weight: bold;
        }
        
        a:hover
        {
            color: #333333;
            text-decoration: none;
            font-weight: bold;
        }
        
        a:active
        {
            color: #006633;
            text-decoration: none;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    @* <table>
        <tr>
            <th>
                Category
            </th>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
                Sku
            </th>
            <th>
                IsAvailable
            </th>
            <th>
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Truncate(item.Name, 150)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sku)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsAvailable)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }
    </table>*@
    @{
        var list = Model.Take(50);
        var grid = new WebGrid(source: Model, rowsPerPage: 20, canPage: true, canSort: true);
        var pager = grid.Pager().ToString();
        var newpager = System.Text.RegularExpressions.Regex.Replace(pager, "(\\d+) ", "<span class='selected'>$1</span>");
    }
    @grid.GetHtml(columns: grid.Columns(
        grid.Column("Sku", format: @<text> @Html.ActionLink((string)item.Sku, "Edit", new {id = item.ID})</text>),
        grid.Column("Name"),
        grid.Column("Price", format: @<text>@item.Price.ToString("C")</text>),
        grid.Column("IsAvailable", format: @<text>@item.IsAvailable</text>),
        grid.Column("Delete", format: @<text><a href="@Url.Action("DeleteConfirmed", "EditProduct", new { id = item.id })" onclick="javascript:return ConfirmDelete();"><img
            src="../../cssimage/delete.png" alt="" style="border: none;" /></a></text>)
    ))
    <script type="text/javascript">
        function ConfirmDelete() {
            return confirm("Are you sure you want to delete this product?");
        }
    </script>
</body>
</html>